# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Restaurant.delete_all

# Restaurant.create(address: "", open: ,.00 close: ,.00 name: "", menu: [{:name => '', :price => , :description => '', :rating => , :category => '', :pictures => [], :featured => false}])




pekinggourmet = Restaurant.create(pic_url: 'https://peking.typografik.com/wp-content/uploads/2014/07/about4.jpg',rating: 5,featured: false, address: "6029 Leesburg Pike Falls Church, VA 22041-2203",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 11.00, close: 22.00, hours_string: '11AM - 10PM',name: "Peking Gourmet Inn",menu_item: ['Seafood Imperial','Biltong','French Fries','Sushirrito','Chicken Larb'], menu_price: [40,19,6,9,18], menu_description: ['Generous portions of snow crab, jumbo shrimp & sea scallop in a light garlic sauce.','Spicy dried and cured Kudu meat. Homemade!','Julienned Russet potatoes, fried to a perfect golden crisp in beef fat.','Choose from Spicy Tuna, Spicy Salmon, Salmon and Avocado or California Roll, rolled in one large piece like a delicious oriental burrito','Fragrant lemongrass, chilies and a sweet and tangy sauce flavor this classic Thai appetizer.'], menu_rating: [4.7,4.3,5,4,4.8], menu_category: ['Seafood'], menu_pictures: [], menu_featured: [false])
honeypig = Restaurant.create(pic_url: 'https://3.bp.blogspot.com/-jTxryiK8y_g/VLSfrsFQVOI/AAAAAAAAZyA/XSHlPNPXO8c/s1600/IMG_3409.JPG',rating: 4.2,featured: false, address: "7220 Columbia Pke, Annandale, VA 22003",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 0.00, close: 0.00, hours_string: '24/7',name: "Honey Pig",menu_item: ['Meat Tornado','Tofu','Fried Rice','Soup du jour','Thinly Sliced Duck Breast'], menu_price: [9,7,9,6,9], menu_description: ['A perfect storm of beef, chicken, steak, bison and pork. Please consult your doctor prior to ordering to find out if consumption of The Meat Tornado is advised.','A disturbing amount of bean curd.','An unconventional quantity of rice, fried with duck fat, vegetables and one egg.','It means "Soup of the day".','Thinly sliced duck breast brought to you fresh and raw ready to be BBQ\' for freshest of taste. (Why would we deliver raw duck meat? Why not!?  This is America.)'], menu_rating: [5,4.1,5,4.2,4.3], menu_category: ['Meat'], menu_pictures: [], menu_featured: [false])
uma = Restaurant.create(pic_url: 'https://media-cdn.tripadvisor.com/media/photo-s/08/67/44/be/bali-safari-marine-park.jpg',rating: 4.5,featured: true, address: "9380 Baltimore National Pike, Ellicott City, MD 21042",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 11.00, close: 22.00, hours_string: '11AM - 10PM',name: "Uma Uma", menu_item: ['Pad Thai','Meatloaf Grilled Cheese','Supa Hot Noodle','Edamame','Flan'], menu_price: [12,9.95,9.99,3], menu_description: ['Stir Fried noodles, spicy nuts with scrambled eggs and hoison sauce.','Homemade meatloaf on your choice of bread and cheese.  Recommend provolone, jack, or gouda.','House made flat noodle, but you’ll swear they were forged in the sculleries of Hell. Here comes the fire.','Give Peas a chance','A custard-based dessert'], menu_rating: [4], menu_category: ['Soup'], menu_pictures: [], menu_featured: [false])
captainGeorge = Restaurant.create(pic_url: 'https://captaingeorges.com/application/files/8714/6973/2362/facebook.jpg',rating: 3.5,featured: false, address: "5363 Richmond Rd, Williamsburg, VA 23188",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velietus risus et est. Also we\'re located in Williamsburg. Can\'t believe we would deliver to DC but we found a way.', open: 3.00, close: 22.00 , hours_string: '3PM - 10PM',name: "Captain George Seafood",menu_item: ['Narwhal Ceviche','Hush Puppies','Chalupa Supreme','Mako Shark Filet','Fish Tacos','Fried Select Oysters','Sous Vide Skate Steak'], menu_price: [50,5,3,30,9,15,38], menu_description: ['Locally raised, free range organic Narwhal. Prepared ceviche style with lime, avocado, salt, onion, fresh mango. Imagine eating a small slice of citrus-cured baby angle. Delicious. PLEASE ALLOW 4 HOURS FOR DELIVERY BECAUSE WE HAVE TO HUNT IT AND THEN WE ARE LOCATED IN WILLIAMSBURG OF ALL PLACES.','Scrumptious bits of spiced and fried cornmeal. Fried until golden brown in house-made special fry oil.','A lightly fried shell surrounds an awkward amount of seasoned beef, sour cream, lettuce, onion, tomato and special sauce.','A peculiarly sized filet of locally caught Mako Shark. Eating an apex predator brings a visceral and exciting experience to any meal!','An unexpected trio of Mahi Mahi, Tilapia and Patagonian Toothfish. Served with plenty of cilantro, lime, onion and red lettuce. We\'ve never experienced any complaints.','Daily changed oysters','A cornucopia of flavor. Also, if you can say the name 7 times quickly, it will still be the same price. Finished in a cast iron skillet that has personally made the yearly pilgrimage to Flavortown.'], menu_rating: [5,5,4.1,4.9,3.9,4.2,5], menu_category: ['Seafood'], menu_pictures: [], menu_featured: [false])
bonchon = Restaurant.create(pic_url: 'https://a.mktgcdn.com/p/fuQlooZEdMIDJ4F7z4v9Ms-aggAkF5FJIOcqOn1fN4c/800x599.jpg',rating: 4.1,featured: true, address: "1015 Half St SE, Washington, DC 20003",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 11.00, close: 22.00, hours_string: '11AM - 10PM',name: "Bonchon",menu_item: ['Hot Spicy Duckling','Crispy Beef','Sea Cucumber Salad','Hot Thighs','Bon Scott\'s Noodles','S?','Fried Ice Cream','Wings',], menu_price: [12,10,16,10,9,20,5,29], menu_description: ['A slightly unorthodox serving of an entire duckling that has been very naughty. Spicy.','An inhumane pile of thinly sliced beef, lightly breaded and caramelized and then tossed in sesame seeds. Drowned in an ocean of spicy soy sauce.','Believed in Ancient Greece to be a symbol of fertility and a strong ability to breathe underwater. NB: Sea Cucumber is not a vegetable. I\'m not sure they\'re sentient, but they are scientifically alive. Weird, slimy, tubular sea meat.','TWELVE POUNDS OF FRIED CHICKEN THIGHS. Available from white person hot, to raised in a cave in Peru heat.','A familiar heap of fresh made noodles, tossed in a bourbon sauce that we guarantee will make you unfit to operate heavy machinery. Please consider calling an uber to get home.','What is S? Where did it come from? All we know, is that we have a frozen box labeled "S". We will prepare what is inside however you want.','We found a way to fry ice cream. If that doesn\'t get your senses tingling, please leave.','Korean BBQ Fried Chicken Wings'], menu_rating: [5,4.1,3.2,4.5,4.99,1,5,4],menu_category: ['Meat'], menu_pictures: [], menu_featured: [false])
miPeru = Restaurant.create(pic_url: 'https://www.solomujeresm.com/wp-content/uploads/2016/04/1._Lomo_Saltado.jpg',rating: 4.3,featured: true, address: "18216 Flower Hill WayGaithersburg, MD 20879",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 11.00, close: 22.00, hours_string: '11AM - 10PM',name: "Mi Peru", menu_item: ['Pad Thai','Meatloaf Grilled Cheese','Supa Hot Noodle','Edamame','Flan'], menu_price: [12,9.95,9.99,3], menu_description: ['Stir Fried noodles, spicy nuts with scrambled eggs and hoison sauce.','Homemade meatloaf on your choice of bread and cheese.  Recommend provolone, jack, or gouda.','House made flat noodle, but you’ll swear they were forged in the sculleries of Hell. Here comes the fire.','Give Peas a chance','A custard-based dessert'], menu_rating: [5], menu_category: ['Stir Fry'], menu_pictures: [], menu_featured: [false])
daikokuya = Restaurant.create(pic_url: 'https://inagoodfoodmood.files.wordpress.com/2013/01/img_3022.jpg',rating: 4.5,featured: true, address: "327 E 1st St, Los Angeles, CA 90012",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 11.00, close: 24.00, hours_string: '11AM - 12AM',name: "Daikokuya", menu_item: ['Tuna Sashimi Bowl','Sesame Surprise!','Squid ravioli in a lemon grass broth with goat cheese profiteroles','Swordfish meat loaf with onion marmalade','Rare roasted partridge breast in raspberry coulis with a sorrel timbale','Grilled free-range rabbit with herb french fries'], menu_price: [15.95,12,11,10,20,45], menu_description: ['Slices of raw tuna over a bowl of sushi rice. served with miso soup and salad','Be our guest and find out the secrets of the Far East in this tempting little dish','Delightful and briny. Prepared fresh.','Limited Quantities. This is flying off the menu faster than we can serve it! Decadent and lush','It’s pretty good','Get this while it lasts. Spicy, Gamey and a real treat'], menu_rating: [5,5,5,5,5,5], menu_category: ['Soup'], menu_pictures: [], menu_featured: [false])
saigon = Restaurant.create(pic_url: 'https://s3-media2.fl.yelpcdn.com/bphoto/L_pB9fvK8eOn158O3jLrvA/o.jpg',rating: 5,featured: false, address: "6218 Wilson Blvd, Falls Church, VA 22044",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 10.00, close: 20.00 , hours_string: '11AM - 8PM',name: "Little Saigon Restaurant", menu_item: ['Pad Thai','Meatloaf Grilled Cheese','Supa Hot Noodle','Edamame','Flan'], menu_price: [12,9.95,9.99,3,5], menu_description: ['Stir Fried noodles, spicy nuts with scrambled eggs and hoison sauce.','Homemade meatloaf on your choice of bread and cheese.  Recommend provolone, jack, or gouda.','House made flat noodle, but you’ll swear they were forged in the sculleries of Hell. Here comes the fire.','Give Peas a chance','A custard-based dessert'], menu_rating: [3,4.2,3,], menu_category: ['Deserts'], menu_pictures: [], menu_featured: [false])
taraThai = Restaurant.create(pic_url: 'https://tarathai.com/homepage/wp-content/uploads/2016/01/POST01.jpg',rating: 4,featured: false, address: "4849 Massachusetts Ave NW, Washington, DC 20016",description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ornare, tortor sed finibus pretium, mauris velit viverra leo, at finibus metus risus et est.', open: 11.00, close: 22.00, hours_string: '11AM - 10PM',name: "Tara Thai", menu_item: ['Pad Thai','Meatloaf Grilled Cheese','Supa Hot Noodle','Edamame','Flan'], menu_price: [12,9.95,9.99,3], menu_description: ['Stir Fried noodles, spicy nuts with scrambled eggs and hoison sauce.','Homemade meatloaf on your choice of bread and cheese.  Recommend provolone, jack, or gouda.','House made flat noodle, but you’ll swear they were forged in the sculleries of Hell. Here comes the fire.','Give Peas a chance','A custard-based dessert'], menu_rating: [3.5,5,4.6,4,3.2], menu_category: [], menu_pictures: [], menu_featured: [false])
